name: narkdown

on:
  schedule:
    - cron: 0 0 * * * # at 00:00 AM (UTC) on everyday.
  push:
    branches:
      - ci/**
  workflow_dispatch: {}

jobs:
  narkdown:
    name: narkdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: awesome-reading-list
        uses: narkdown/awesome-reading-list@main
        with:
          database-id: ${{ secrets.NOTION_DATABASE_ID }}
          notion-api-key: ${{ secrets.NOTION_API_TOKEN }}
          target-file-path: awesome-reading-list.md

      - uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          gist_file_name: awesome-reading-list.md
          file_path: awesome-reading-list.md
