name: notion2github

on:
  schedule:
    - cron: '0 0 * * *' # KST 9:00 AM on everyday
  push:
    branches:
      - 'ci/**'
  workflow_dispatch: {}

jobs:
  notion2github:
    name: notion2github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: 'Get Reading List'
        env:
          NOTION_KEY: '${{ secrets.NOTION_KEY }}'
          DATABASE_ID: '${{ secrets.DATABASE_ID }}'
        run: 'yarn start'
      - name: 'Format documents'
        run: 'yarn format'
      - uses: 'EndBug/add-and-commit@v7'
        with:
          message: 'docs: updated by notion2github'
          default_author: github_actions
